
# Create Pods and Services
#
# oc apply -f etc/k8s/ticker2log-deployment.yaml 


# Artemis Pod #########################################################################################################
#
---
apiVersion: v1
kind: Pod
metadata:
  name: artemis
  labels:
    app: ticker2log
    pod: artemis
spec:
  containers:
    - name: activemq-artemis2
      image: quay.io/nessusio/activemq-artemis:2.16.0
      env:
       - name: ARTEMIS_USERNAME
         value: 'artemis'
       - name: ARTEMIS_PASSWORD
         value: 'artemis'
      ports:
        - containerPort: 1883  # MQTT
          protocol: TCP
        - containerPort: 5445  # HORNETQ,STOMP
          protocol: TCP
        - containerPort: 5672  # AMQP
          protocol: TCP
        - containerPort: 8161  # Web Server
          protocol: TCP
        - containerPort: 9404  # JMX Exporter
          protocol: TCP
        - containerPort: 61613 # STOMP
          protocol: TCP
        - containerPort: 61616 # CORE,MQTT,AMQP,HORNETQ,STOMP,OPENWIRE
          protocol: TCP
      volumeMounts:
        - name: artemis-instance
          mountPath: /var/lib/artemis-instance
  volumes:
    - name: artemis-instance
      emptyDir: {}

# Artemis Service 
---
apiVersion: v1
kind: Service
metadata:
  name: artemis
  labels:
   app: ticker2log
spec:
  selector:
    app: ticker2log
    pod: artemis
  ports:
    - name: tcp
      port: 61616
 
# Kafka Pod ###########################################################################################################
#
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: ticker2log
    pod: kafka
spec:
  containers:
  - name: kafka
    image: quay.io/bitnami/kafka:2.8.0
    env:
      - name: ALLOW_PLAINTEXT_LISTENER
        value: 'true'
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: $(ZOOKEEPER_SERVICE_HOST):$(ZOOKEEPER_SERVICE_PORT)
      - name: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT://$(KAFKA_SERVICE_HOST):9092
      - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: '1'
      - name: KAFKA_BROKER_ID
        value: '1'
    ports:
    - name: tcp
      containerPort: 9092

# Kafka Service 
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: ticker2log
spec:
  selector:
    app: ticker2log
    pod: kafka
  ports:
  - name: tcp
    port: 9092

# Zookeeper Pod #######################################################################################################
#
---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: ticker2log
    pod: zookeeper
spec:
  containers:
  - name: zookeeper
    image: quay.io/bitnami/zookeeper:3.7.0
    env:
      - name: ALLOW_ANONYMOUS_LOGIN
        value: 'true'
      - name: ZOOKEEPER_CLIENT_PORT
        value: '2181'
    ports:
    - containerPort: 2181

# Zookeeper Service 
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: ticker2log
spec:
  selector:
    app: ticker2log
    pod: zookeeper
  ports:
  - name: tcp
    port: 2181

# Application Pod #####################################################################################################
#
---
apiVersion: v1
kind: Pod
metadata:
  name: camel
  labels:
    app: ticker2log
    pod: camel
spec:
  containers:
    - name: camel
      image: quay.io/nessusio/fuse-booster-camel-quarkus-ticker-amq-kafka
      imagePullPolicy: Always
      env:
        - name: TICKER2LOG_XCHANGE_CURRENCYPAIR
          value: 'ADA/USDT'
        - name: TICKER2LOG_ARTEMIS_SERVICE_HOST
          value: $(ARTEMIS_SERVICE_HOST)
        - name: TICKER2LOG_ARTEMIS_USERNAME
          value: 'artemis'
        - name: TICKER2LOG_ARTEMIS_PASSWORD
          value: 'artemis'
        - name: TICKER2LOG_ARTEMIS_QUEUE
          value: 'artemis'
        - name: TICKER2LOG_KAFKA_SERVICE_HOST
          value: $(KAFKA_SERVICE_HOST)
        - name: TICKER2LOG_KAFKA_TOPIC
          value: 'ticker'
 
